name: api-serenity-test-run
on:
  push:
    paths:
      - 'src/test/**'
  schedule:
    - cron: '0 8 * * 1,4'
env:
  USER: ${{ secrets.USER }}
  PASSWORD: ${{ secrets.PASSWORD }}
  AUTHORIZATION: ${{ secrets.AUTHORIZATION }}
jobs:
  test-run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: ./gradlew
      - name: 'api serenity test result'
        uses: actions/upload-artifact@v3
        with:
          name: api-serenity-test-result
          path: target/site
          retention-days: 3