name: api-serenity-test-run
on:
  push:
    paths:
      - 'src/test/**'
  schedule:
    - cron: '0 8 * * 1,4'
env:
  USER: ${{ secrets.USER }}
  PASSWORD: ${{ secrets.PASSWORD }}
  AUTHORIZATION: ${{ secrets.AUTHORIZATION }}
jobs:
  test-run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 22 for x64
        uses: actions/setup-java@v4
        with:
          java-version: '22'
          distribution: 'temurin'
          architecture: x64
      - name: 'Run API tests'
        run: ./gradlew
      - name: 'API serenity test result'
        uses: actions/upload-artifact@v4
        with:
          name: api-serenity-test-result
          path: target/site
          retention-days: 3